---
title: "UAC Demo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(plotly)

course_df <- read_csv('data/courses.csv') %>% mutate(course_code = str_pad(course_code, width = 6, pad = '0'))
tsne_df <- read_csv('data/area_of_study_tsne.csv') %>% mutate(course_code = str_pad(course_code, width = 6, pad = '0'))
```

## Area of Study


```{r, out.width="100%"}
ggplotly(
  tsne_df %>%
    inner_join(course_df %>% select(course_code, uni_code, course_name, course_field), by = 'course_code') %>%
    filter(!str_detect(course_name, '/')) %>% # ignore double degrees
    filter(uni_code %in% c('unsw', 'usyd', 'uts', 'mq', 'ws', 'acu')) %>%
    # filter(uni_code == 'unsw') %>%
    ggplot(aes(x = tSNE1, y = tSNE2, text = course_name, color = course_field)) +
    geom_point() +
    labs(color = '') +
    theme_bw() +
    theme(
      legend.position="bottom",
      axis.title=element_blank(),
      axis.text=element_blank(),
      axis.ticks=element_blank()
    )
)

```
